server:
  port: 8091

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:mongoDB@graphql.m3ros.mongodb.net/test?retryWrites=true
      database: pharmacy-db
  application:
    name: MEMBER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


